#!/usr/bin/env python3
"""Drop duplicate chunk texts from the tier-2 corpus index (2026-07-27).

A document archive holds the same text under several filenames. In this vault
the starkest case was `ilovepdf_merged (1).pdf.md`, a 34 MB concatenation of
other documents: 1,987 chunks — 10.7% of the raw index — of which 93% of the
distinct chunk texts appear verbatim in a standalone document. Left in, it
crowded the top of result lists with a grab-bag copy of documents the corpus
already held properly, and returned the same passage two or three times.

Rule: when one normalized chunk text appears in several documents, keep the
copy in the document with the FEWEST chunks. The narrowest document is the
most likely canonical source; a merged blob, being largest, always loses.
Ties break on path so the result is deterministic.

Duplicates are RECORDED, not moved (changed 2026-07-28). --apply writes their
chunk ids to chunks-duplicates.json; corpus-bm25.py loads that manifest and
leaves them out of the index. The decision stays auditable and reversible —
delete the manifest and rebuild to undo it.

Moving the files, as this script used to, emptied them out of chunks/ and so
broke two other tools that treat chunks/ as the complete set: corpus-index.py
saw those documents as un-chunked and regenerated every one on the next run
(~3,000 pointless writes, and "wrote=" stopped meaning anything), while
prune_corpus_chunks.py could not see them at all — so deleting a document that
had WON a dedup stranded the loser's only copy outside the index, silently
losing text belonging to a document still on disk.

Only chunks of >=400 normalized chars are compared; short chunks (headers,
page furniture) collide for uninteresting reasons.

Usage:
    corpus-dedup.py [--apply]      (dry-run unless --apply)
"""
import argparse
import collections
import glob
import hashlib
import json
import os
import re
import sys
from pathlib import Path

VAULT_ROOT = Path(__file__).resolve().parent.parent
CORPUS = VAULT_ROOT / ".vault-meta" / "corpus"
CHUNKS = CORPUS / "chunks"
MANIFEST = CORPUS / "chunks-duplicates.json"
MIN_CHARS = 400


def norm(s):
    return re.sub(r"\W+", "", s.lower())


def main():
    ap = argparse.ArgumentParser(description="Dedupe tier-2 corpus chunks.")
    ap.add_argument("--apply", action="store_true",
                    help="Write the duplicate manifest (default is dry-run)")
    args = ap.parse_args()

    if not CHUNKS.is_dir():
        print(f"ERR: no corpus chunks at {CHUNKS}. Run corpus-index.py first.",
              file=sys.stderr)
        return 2

    by_hash = collections.defaultdict(list)   # hash -> [(page, file, chunk_id)]
    per_doc = collections.Counter()           # page -> total chunks
    scanned = 0

    for f in glob.glob(str(CHUNKS / "*" / "chunk-*.json")):
        try:
            rec = json.loads(open(f, encoding="utf-8").read())
        except (OSError, ValueError):
            continue
        page = rec.get("page_path", "?")
        per_doc[page] += 1
        text = norm(rec.get("raw_text", ""))
        if len(text) < MIN_CHARS:
            continue
        address, idx = rec.get("page_address"), rec.get("chunk_index")
        if address is None or idx is None:
            continue          # same guard bm25-index.py applies
        scanned += 1
        by_hash[hashlib.sha1(text.encode()).hexdigest()].append(
            (page, f, f"{address}:{idx}"))

    losers = []
    for entries in by_hash.values():
        if len(entries) < 2:
            continue
        entries.sort(key=lambda e: (per_doc[e[0]], e[0], e[1]))
        losers.extend(entries[1:])

    dropped = collections.Counter(p for p, _f, _cid in losers)
    print(f"chunks compared (>={MIN_CHARS} norm chars): {scanned}")
    print(f"redundant copies to exclude: {len(losers)}")
    print("\ntop documents losing chunks:")
    for page, n in dropped.most_common(8):
        name = page.replace("\\", "/").split("/")[-1][:64]
        print(f"  {n:5d} of {per_doc[page]:5d}  {name}")

    if not args.apply:
        print("\n(dry run — pass --apply to write the manifest)")
        return 0

    ids = sorted({cid for _page, _f, cid in losers})
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    tmp = MANIFEST.with_suffix(f".{os.getpid()}.tmp")
    tmp.write_text(json.dumps({
        "note": "Chunk ids corpus-bm25.py leaves out of the index. "
                "Regenerated by corpus-dedup.py --apply; delete and rebuild "
                "to restore every chunk.",
        "min_chars": MIN_CHARS,
        "duplicate_chunk_ids": ids,
    }, indent=2), encoding="utf-8")
    os.replace(tmp, MANIFEST)
    print(f"\nwrote {len(ids)} duplicate chunk ids to {MANIFEST}")
    print("No files were moved — chunks/ stays complete.")
    print("Now re-run: corpus-bm25.py build")
    return 0


if __name__ == "__main__":
    sys.exit(main())
